apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-front
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-front
  template:
    metadata:
      labels:
        app: ecommerce-front
    spec:
      containers:
      - name: python-app
        image: docker.io/library/rocket:local
        imagePullPolicy: Never
        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: ecommerce-configmap
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 2048Mi
            cpu: 450m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-configmap
  namespace: prod
data:
  DB_ENGINE: "mysql"
  DB_HOST: "mariadb"
  DB_NAME: "ecommerce"
  DB_USERNAME: "root"
  DB_PASS: "SuperSecurePass123"
  DB_PORT: "3306"
  STRIPE_SECRET_KEY: "sk_test_..."
  STRIPE_PUBLISHABLE_KEY: "pk_..."
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-front-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: ecommerce-front
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 5005
    nodePort: 30005
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mariadb-pv
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/data/mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb-pvc
    namespace: prod
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mariadb-config
    namespace: prod
    labels:
        app: mariadb
data:
    my.cnf: |
        [mysqld]
        bind-address=0.0.0.0
        default_storage_engine=InnoDB
        innodb_file_per_table=1
        max_connections=1000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "SuperSecurePass123"
        - name: MYSQL_DATABASE
          value: "ecommerce"
        image: mariadb:latest
        name: mariadb
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-storage
        - mountPath: /etc/mysql/conf.d
          name: config-volume
      volumes:
      - configMap:
          name: mariadb-config
        name: config-volume
  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
    name: mariadb
    namespace: prod
spec:
    ports:
    - port: 3306
      targetPort: 3306
    selector:
      app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: prod
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: mariadb
        - name: PMA_PORT
          value: "3306"
        - name: PMA_ARBITRARY
          value: "1"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: prod
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
  selector:
    app: phpmyadmin